spring:

  datasource:
    url:      jdbc:mysql://localhost:3306/profit
    username: root
    password: root
    name: profit

  # Spring Data JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

